# Embeds IOP modules (.irx) into the ELF as C byte arrays, so the game can
# load them with SifExecModuleBuffer without needing files next to the ELF.
# For each module `foo.irx` it emits:
#   const unsigned char foo_irx[];  const unsigned int foo_irx_size;
function(ps2_embed_irx OUT_C)
	set(code "/* Auto-generated by cmake/ps2_embed_irx.cmake — do not edit. */\n")
	foreach(irx ${ARGN})
		if(NOT EXISTS ${irx})
			message(FATAL_ERROR "ps2_embed_irx: missing module ${irx}")
		endif()
		get_filename_component(name ${irx} NAME_WE)
		file(READ ${irx} hex HEX)
		string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes ${hex})
		string(APPEND code "const unsigned char ${name}_irx[] __attribute__((aligned(16))) = {${bytes}};\n")
		string(APPEND code "const unsigned int ${name}_irx_size = sizeof(${name}_irx);\n")
		message(STATUS "Embedding IOP module: ${irx}")
	endforeach()
	file(WRITE ${OUT_C} "${code}")
endfunction()
