#ifdef PS2_PLATFORM

#include "Ps2PvzServices.h"

#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <iopcontrol.h>
#include <iopheap.h>
#include <sbv_patches.h>
#include <libmc.h>
#include <libcdvd.h>
#include <delaythread.h>
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

#include <string>

// Embedded IOP modules (generated by cmake/ps2_embed_irx.cmake).
extern "C" {
extern const unsigned char usbd_irx[];
extern const unsigned int  usbd_irx_size;
extern const unsigned char usbhdfsd_irx[];
extern const unsigned int  usbhdfsd_irx_size;
extern const unsigned char audsrv_irx[];
extern const unsigned int  audsrv_irx_size;
extern const unsigned char iomanX_irx[];
extern const unsigned int  iomanX_irx_size;
extern const unsigned char fileXio_irx[];
extern const unsigned int  fileXio_irx_size;
extern const unsigned char bdm_irx[];
extern const unsigned int  bdm_irx_size;
extern const unsigned char bdmfs_fatfs_irx[];
extern const unsigned int  bdmfs_fatfs_irx_size;
extern const unsigned char usbmass_bd_irx[];
extern const unsigned int  usbmass_bd_irx_size;
extern const unsigned char cdfs_irx[];
extern const unsigned int  cdfs_irx_size;

// fileXio EE client (fileXio_rpc.h) + the ps2sdk libc hook that reroutes
// newlib's open/mkdir/dopen/... through fileXio so iomanX-registered devices
// (BDM's mass:) are reachable. The hook symbol lives in libfileXio.a but has
// no public header.
int fileXioInit(void);
}

static std::string s_savePrefix;
static std::string s_resourcePrefix; // "" = cwd; "cdfs:/" on a CD/DVD boot
static bool s_audioAvailable = false;

static void ps2_load_rom_module(const char* path)
{
    int ret = SifLoadModule(path, 0, NULL);
    printf("[PS2] SifLoadModule %s -> %d\n", path, ret);
}

static bool ps2_load_embedded_module(const char* name, const unsigned char* mod, unsigned int size)
{
    int modRes = 0;
    int ret = SifExecModuleBuffer((void*)mod, size, 0, NULL, &modRes);
    printf("[PS2] SifExecModuleBuffer %s -> ret=%d res=%d\n", name, ret, modRes);
    return ret >= 0 && modRes != 1; // 1 = module returned NO RESIDENT END
}

static bool ps2_dir_usable(const char* path)
{
    DIR* d = opendir(path);
    if (!d)
        return false;
    closedir(d);
    return true;
}

static void ps2_reboot_iop_clean()
{
    // Launchers (uLaunchELF/OPL) leave their own usbd/usbhdfsd/padman resident
    // on the IOP. Our embedded usbd then fails to load and the game silently
    // keeps running on the launcher's aged USB driver, which wedges under
    // sustained load — the roaming freezes seen on real hardware. Reboot the
    // IOP so every driver below is the one we ship.
    while (!SifIopReset("", 0)) {}
    while (!SifIopSync()) {}
    SifInitRpc(0);
}

static void ps2_init_memory_card_stack()
{
    // SIO2MAN is shared with libpad; loading it here makes later pad init cheap.
    ps2_load_rom_module("rom0:SIO2MAN");
    ps2_load_rom_module("rom0:MCMAN");
    ps2_load_rom_module("rom0:MCSERV");
    mcInit(MC_TYPE_MC);
}

static bool ps2_init_usb_mass(bool theHostFs)
{
    // PCSX2/ps2link run from host:, whose HLE only covers the classic fio RPC —
    // rerouting newlib through fileXio there would break host: access. Keep the
    // legacy stack on emulators; the BDM stack below targets real hardware.
    if (!ps2_load_embedded_module("usbd.irx", usbd_irx, usbd_irx_size))
        return false;

    if (!theHostFs)
    {
        // Modern BDM stack (what OPL uses): bdmfs_fatfs registers "mass:" on
        // iomanX, so newlib IO must be rerouted through fileXio to reach it;
        // iomanX mirrors classic ioman devices (mc0:, rom0:), so those keep
        // working after the switch.
        if (ps2_load_embedded_module("iomanX.irx", iomanX_irx, iomanX_irx_size)
            && ps2_load_embedded_module("fileXio.irx", fileXio_irx, fileXio_irx_size))
        {
            fileXioInit();

            if (ps2_load_embedded_module("bdm.irx", bdm_irx, bdm_irx_size)
                && ps2_load_embedded_module("bdmfs_fatfs.irx", bdmfs_fatfs_irx, bdmfs_fatfs_irx_size)
                && ps2_load_embedded_module("usbmass_bd.irx", usbmass_bd_irx, usbmass_bd_irx_size))
            {
                printf("[PS2] USB stack: BDM (usbmass_bd + bdmfs_fatfs)\n");
                return true;
            }
            // BDM failed to come up; the fileXio reroute stays (harmless —
            // iomanX mirrors ioman) and we fall back to the legacy driver.
        }
    }

    // Legacy stack: usbd + usbhdfsd registers "mass:" on plain ioman.
    printf("[PS2] USB stack: legacy usbhdfsd\n");
    return ps2_load_embedded_module("usbhdfsd.irx", usbhdfsd_irx, usbhdfsd_irx_size);
}

static bool ps2_wait_for_mass_device(int theMaxTenths)
{
    // Give a plugged-in USB stick time to enumerate + mount. After the IOP
    // reboot the device re-enumerates from scratch, so poll in 100ms steps but
    // return as soon as it answers. On a CD/DVD boot USB is only an optional
    // save target, so the caller uses a short budget to avoid a long black
    // screen when no stick is present (saves fall through to the memory card).
    for (int i = 0; i < theMaxTenths; i++)
    {
        if (ps2_dir_usable("mass:"))
            return true;
        DelayThread(100 * 1000);
    }
    return false;
}

// Loads the cdfs file driver so the disc is reachable as "cdfs:/...". cdfs is
// case-insensitive and takes forward slashes, so the game's existing relative
// asset paths work once prefixed with the cdfs root — no cdrom0: uppercase/
// backslash/";1" mangling, which is what broke the raw cdrom0: boot. cdvdman is
// already resident (it answers the classic cdrom0: probes), and sceCdInit binds
// the CD RPC before cdfs queries the disc. Only called on a CD boot, where a
// disc is guaranteed present, so sceCdInit will not block waiting for media.
//
// Returns the working device root (ending so that root+"main.pak" opens), or ""
// if cdfs never came up. The spelling of the cdfs root differs slightly across
// driver revisions, so probe the shipped main.pak with each candidate and adopt
// whichever the driver actually accepts instead of hard-coding one.
static const char* ps2_init_cdfs()
{
    sceCdInit(SCECdINIT);
    if (!ps2_load_embedded_module("cdfs.irx", cdfs_irx, cdfs_irx_size))
        return "";

    static const char* kRoots[] = { "cdfs:/", "cdfs:", "cdfs:\\" };
    for (int aTry = 0; aTry < 50; aTry++) // up to ~5s for the tray/laser
    {
        for (unsigned i = 0; i < sizeof(kRoots) / sizeof(kRoots[0]); i++)
        {
            std::string aPath = std::string(kRoots[i]) + "main.pak";
            FILE* f = fopen(aPath.c_str(), "rb");
            if (f != NULL)
            {
                fclose(f);
                printf("[PS2] cdfs root: '%s' (main.pak found)\n", kRoots[i]);
                return kRoots[i];
            }
        }
        DelayThread(100 * 1000);
    }
    printf("[PS2] cdfs: main.pak not found under any root\n");
    return "";
}

// Note: the debug log is NOT opened at the boot prefix. It opens exactly once,
// at the final app-data location (<cwd>/savedata/userdata/log.txt, set by
// TodAssertInitForApp); until then printf lines wait in the early-log buffer
// (TodDebug.cpp). One log.txt, one location.
static bool ps2_try_usb_save_prefix()
{
    mkdir("mass:/PVZ", 0777);
    if (!ps2_dir_usable("mass:/PVZ"))
        return false;

    s_savePrefix = "mass:/PVZ/";
    return true;
}

static bool ps2_try_memory_card_save_prefix()
{
    mkdir("mc0:/PVZ", 0777);
    if (!ps2_dir_usable("mc0:/PVZ"))
        return false;

    s_savePrefix = "mc0:/PVZ/";
    return true;
}

static void ps2_init_audio()
{
    // audsrv needs the ROM sound library loaded first.
    ps2_load_rom_module("rom0:LIBSD");
    s_audioAvailable = ps2_load_embedded_module("audsrv.irx", audsrv_irx, audsrv_irx_size);
}

void Ps2PvzInitServices(const char* theArgv0)
{
    static bool sDone = false;
    if (sDone)
        return;
    sDone = true;

    SifInitRpc(0);

    // Decide BEFORE the reboot: host: is served by the launcher/emulator side,
    // so it must be probed while that side is still alive. PCSX2/ps2link keep
    // the legacy stack (their HLE never wedges and a reboot would sever host:).
    bool aHostFs = ps2_dir_usable("host:.");

    // Booted from a CD/DVD (or a mounted ISO) iff argv[0] names cdrom0:. This is
    // independent of host:: PCSX2 exposes host: even while booting an ISO, so it
    // must NOT gate CD detection (that bug made cdfs never load under PCSX2).
    // On a CD boot the launcher's cwd (cdrom0:) is useless for both reads (path
    // mangling) and writes (read-only), so assets go through cdfs and saves to
    // the memory card / USB.
    bool aCdBoot = theArgv0 != NULL && strncmp(theArgv0, "cdrom", 5) == 0;

    if (!aHostFs)
        ps2_reboot_iop_clean();

    SifLoadFileInit();
    SifInitIopHeap(); // SifExecModuleBuffer stages embedded modules in IOP RAM
    sbv_patch_enable_lmb();
    sbv_patch_disable_prefix_check();

    ps2_init_memory_card_stack();

    // On a CD boot USB is only an optional save device, so wait only briefly for
    // it (2s) before falling back to the memory card; otherwise keep the full
    // ~10s enumeration window used when the game is launched from the stick.
    if (ps2_init_usb_mass(aHostFs) && ps2_wait_for_mass_device(aCdBoot ? 20 : 100))
        ps2_try_usb_save_prefix();

    // cdfs is reachable through newlib whether IO is rerouted through fileXio
    // (real-hardware boot) or left on the classic ioman path (PCSX2 host boot),
    // since cdfs registers on ioman and iomanX mirrors it (as mc0:/rom0: do).
    if (aCdBoot)
    {
        const char* aRoot = ps2_init_cdfs();
        if (aRoot[0] != '\0')
            s_resourcePrefix = aRoot;
    }

    ps2_init_audio();

    if (s_savePrefix.empty())
        ps2_try_memory_card_save_prefix();

    // If both fail the prefix stays empty = current directory (PCSX2 host fs,
    // or read-only media: saves fail gracefully but the game runs).

    printf("[PS2] save prefix: '%s'  resource prefix: '%s'  audio: %s\n",
           s_savePrefix.c_str(), s_resourcePrefix.c_str(),
           s_audioAvailable ? "audsrv" : "none");
}

const char* Ps2GetSavePrefix(void)
{
    return s_savePrefix.c_str();
}

const char* Ps2GetResourcePrefix(void)
{
    return s_resourcePrefix.c_str();
}

bool Ps2AudioAvailable(void)
{
    return s_audioAvailable;
}

#endif // PS2_PLATFORM
